namespace TalentLens.Infrastructure.Storage;

/// <summary>Where uploaded CV files live. Swap the implementation for blob storage later.</summary>
public interface IFileStorage
{
    /// <summary>Save a file for an owner (company or seeker profile); returns the stored name to keep on the entity.</summary>
    Task<string> SaveAsync(Guid ownerId, Guid fileId, string extension, Stream content,
        CancellationToken ct = default);

    Stream OpenRead(Guid ownerId, string storedName);

    void Delete(Guid ownerId, string storedName);
}

public sealed class StorageOptions
{
    public const string SectionName = "Storage";

    /// <summary>Folder for uploads. Relative paths are resolved from the app's content root.</summary>
    public string UploadsPath { get; set; } = "App_Data/uploads";

    public int MaxUploadMb { get; set; } = 10;
}

/// <summary>
/// Stores files on local disk as {root}/{ownerId}/{fileId}{ext} (owner = company or job seeker profile). Files are kept outside
/// wwwroot so they are only reachable through an authorized controller action.
/// </summary>
public sealed class LocalFileStorage : IFileStorage
{
    private readonly string _root;

    public LocalFileStorage(string root)
    {
        _root = Path.GetFullPath(root);
        Directory.CreateDirectory(_root);
    }

    public async Task<string> SaveAsync(Guid ownerId, Guid fileId, string extension,
        Stream content, CancellationToken ct = default)
    {
        var ext = extension.ToLowerInvariant();
        if (ext is not (".pdf" or ".docx"))
            throw new ArgumentException($"Unsupported extension {extension}", nameof(extension));

        var storedName = $"{fileId:N}{ext}";
        var dir = Path.Combine(_root, ownerId.ToString("N"));
        Directory.CreateDirectory(dir);
        await using var file = File.Create(Path.Combine(dir, storedName));
        await content.CopyToAsync(file, ct);
        return storedName;
    }

    public Stream OpenRead(Guid ownerId, string storedName) =>
        File.OpenRead(PathFor(ownerId, storedName));

    public void Delete(Guid ownerId, string storedName)
    {
        var path = PathFor(ownerId, storedName);
        if (File.Exists(path)) File.Delete(path);
    }

    private string PathFor(Guid ownerId, string storedName)
    {
        // Stored names are generated by SaveAsync; reject anything that could escape the folder.
        if (string.IsNullOrEmpty(storedName) || storedName != Path.GetFileName(storedName))
            throw new ArgumentException("Invalid stored file name", nameof(storedName));
        return Path.Combine(_root, ownerId.ToString("N"), storedName);
    }
}
