using System.Globalization;

namespace TalentLens.Web.Localization;

/// <summary>
/// UI strings in English and Arabic. Views use <c>@T["Key"]</c> (injected in _ViewImports)
/// and <c>@T.F("Key", args)</c> for formatted strings. The language follows the request
/// culture chosen with the language switcher (cookie). One dictionary keeps every
/// translation side by side, which is easier to maintain than paired .resx files.
/// </summary>
public sealed class UiText
{
    public const string English = "en-US";
    public const string Arabic = "ar-JO"; // Arabic text with the Gregorian calendar

    private static readonly Dictionary<string, (string En, string Ar)> Texts = new()
    {
        // ---------------- navigation / layout
        ["Dashboard"] = ("Dashboard", "لوحة التحكم"),
        ["Overview"] = ("Overview", "نظرة عامة"),
        ["FindJobs"] = ("Find jobs", "ابحث عن وظيفة"),
        ["Jobs"] = ("Jobs", "الوظائف"),
        ["Companies"] = ("Companies", "الشركات"),
        ["Company"] = ("Company", "الشركة"),
        ["Users"] = ("Users", "المستخدمون"),
        ["MyJobs"] = ("My jobs", "وظائفي"),
        ["CvSearch"] = ("CV search", "البحث في السير الذاتية"),
        ["TalentPool"] = ("Talent pool", "بنك المواهب"),
        ["MyApplications"] = ("My applications", "طلباتي"),
        ["SavedJobs"] = ("Saved jobs", "الوظائف المحفوظة"),
        ["MyDashboard"] = ("My dashboard", "لوحتي"),
        ["MyProfile"] = ("My profile", "ملفي الشخصي"),
        ["CompanyProfile"] = ("Company profile", "ملف الشركة"),
        ["PostJob"] = ("Post a job", "انشر وظيفة"),
        ["BackgroundJobs"] = ("Background jobs", "المهام الخلفية"),
        ["Login"] = ("Sign in", "تسجيل الدخول"),
        ["Logout"] = ("Sign out", "تسجيل الخروج"),
        ["Register"] = ("Join now", "سجّل الآن"),
        ["ForEmployers"] = ("For employers", "لأصحاب العمل"),
        ["Tagline"] = ("AI-powered jobs & hiring, in Arabic and English", "وظائف وتوظيف بالذكاء الاصطناعي، بالعربية والإنجليزية"),
        ["Error"] = ("Something went wrong", "حدث خطأ ما"),
        ["ErrorText"] = ("An error occurred while processing your request.", "حدث خطأ أثناء معالجة طلبك."),
        ["BackHome"] = ("Back to home", "العودة للرئيسية"),
        ["AccessDenied"] = ("Access denied", "غير مسموح"),
        ["AccessDeniedText"] = ("Your account doesn't have access to this page.", "حسابك لا يملك صلاحية الوصول لهذه الصفحة."),

        // ---------------- common
        ["Search"] = ("Search", "بحث"),
        ["Save"] = ("Save", "حفظ"),
        ["Unsave"] = ("Saved", "محفوظة"),
        ["Cancel"] = ("Cancel", "إلغاء"),
        ["Edit"] = ("Edit", "تعديل"),
        ["View"] = ("View", "عرض"),
        ["Delete"] = ("Delete", "حذف"),
        ["Update"] = ("Update", "تحديث"),
        ["Filter"] = ("Filter", "تصفية"),
        ["All"] = ("All", "الكل"),
        ["Any"] = ("Any", "الكل"),
        ["ViewAll"] = ("View all", "عرض الكل"),
        ["Name"] = ("Name", "الاسم"),
        ["FullName"] = ("Full name", "الاسم الكامل"),
        ["YourName"] = ("Your name", "اسمك"),
        ["Email"] = ("Email", "البريد الإلكتروني"),
        ["WorkEmail"] = ("Work email", "البريد الإلكتروني للعمل"),
        ["Password"] = ("Password", "كلمة المرور"),
        ["ConfirmPassword"] = ("Confirm password", "تأكيد كلمة المرور"),
        ["Phone"] = ("Phone", "الهاتف"),
        ["Location"] = ("Location", "الموقع"),
        ["Status"] = ("Status", "الحالة"),
        ["Role"] = ("Role", "الدور"),
        ["Joined"] = ("Joined", "تاريخ الانضمام"),
        ["Posted"] = ("Posted", "تاريخ النشر"),
        ["Uploaded"] = ("Uploaded", "تاريخ الرفع"),
        ["Skills"] = ("Skills", "المهارات"),
        ["Languages"] = ("Languages", "اللغات"),
        ["Education"] = ("Education", "التعليم"),
        ["Experience"] = ("Experience", "الخبرة"),
        ["Contact"] = ("Contact", "معلومات التواصل"),
        ["Industry"] = ("Industry", "القطاع"),
        ["Website"] = ("Website", "الموقع الإلكتروني"),
        ["CommaSeparated"] = ("Separate with commas.", "افصل بينها بفواصل."),
        ["YearsShort"] = ("{0:0.#} yrs", "{0:0.#} سنة"),
        ["YearsLong"] = ("{0:0.#} years of experience", "خبرة {0:0.#} سنوات"),
        ["YearsOne"] = ("1 year of experience", "خبرة سنة واحدة"),
        ["YearsPlus"] = ("{0}+ years", "{0}+ سنوات"),
        ["AgoToday"] = ("Today", "اليوم"),
        ["AgoYesterday"] = ("Yesterday", "أمس"),
        ["AgoDays"] = ("{0} days ago", "منذ {0} أيام"),
        ["AgoMonths"] = ("{0} months ago", "منذ {0} أشهر"),

        // ---------------- statuses
        ["StatusPending"] = ("Queued", "في الانتظار"),
        ["StatusProcessing"] = ("Processing", "قيد المعالجة"),
        ["StatusReady"] = ("Ready", "جاهز"),
        ["StatusFailed"] = ("Failed", "فشل"),
        ["AppSubmitted"] = ("Submitted", "مُرسل"),
        ["AppReviewed"] = ("Reviewed", "تمت المراجعة"),
        ["AppShortlisted"] = ("Shortlisted", "في القائمة المختصرة"),
        ["AppInterview"] = ("Interview", "مقابلة"),
        ["AppOffered"] = ("Offer", "عرض عمل"),
        ["AppHired"] = ("Hired", "تم التوظيف"),
        ["AppRejected"] = ("Not selected", "لم يتم الاختيار"),
        ["AppWithdrawn"] = ("Withdrawn", "مسحوب"),
        ["JobDraft"] = ("Draft", "مسودة"),
        ["JobOpen"] = ("Open", "مفتوحة"),
        ["JobClosed"] = ("Closed", "مغلقة"),
        ["TypeFullTime"] = ("Full-time", "دوام كامل"),
        ["TypePartTime"] = ("Part-time", "دوام جزئي"),
        ["TypeContract"] = ("Contract", "عقد"),
        ["TypeInternship"] = ("Internship", "تدريب"),
        ["WorkplaceOnsite"] = ("On-site", "من المكتب"),
        ["WorkplaceRemote"] = ("Remote", "عن بُعد"),
        ["WorkplaceHybrid"] = ("Hybrid", "هجين"),
        ["CompanyStatusPending"] = ("Pending approval", "بانتظار الموافقة"),
        ["CompanyStatusActive"] = ("Active", "نشطة"),
        ["CompanyStatusSuspended"] = ("Suspended", "موقوفة"),
        ["CompanyPendingTitle"] = ("Your company is awaiting approval", "شركتك بانتظار موافقة الإدارة"),
        ["CompanyPendingText"] = ("You can prepare job drafts and use the talent pool now. Jobs go live once the TalentLens team approves your company.", "يمكنك إعداد مسودات الوظائف واستخدام بنك المواهب الآن. تُنشر الوظائف بعد موافقة فريق TalentLens على شركتك."),
        ["CompanySuspendedTitle"] = ("Your company is suspended", "تم إيقاف شركتك"),
        ["CompanySuspendedText"] = ("Your jobs are hidden from job seekers. Contact the TalentLens team.", "وظائفك مخفية عن الباحثين عن عمل. تواصل مع فريق TalentLens."),
        ["RoleAdmin"] = ("Admin", "مدير المنصة"),
        ["RoleRecruiter"] = ("Recruiter", "مسؤول توظيف"),
        ["RoleJobSeeker"] = ("Job seeker", "باحث عن عمل"),

        // ---------------- home / public
        ["HeroTitle"] = ("Find your next job — the smart way", "اعثر على وظيفتك القادمة بذكاء"),
        ["HeroText"] = ("Thousands of opportunities across the region. Upload your CV once and let AI show you how well you match every job.", "فرص عمل في جميع أنحاء المنطقة. ارفع سيرتك الذاتية مرة واحدة ودع الذكاء الاصطناعي يوضح مدى تطابقك مع كل وظيفة."),
        ["JobKeywordPlaceholder"] = ("Job title, skill or company", "المسمى الوظيفي، المهارة أو الشركة"),
        ["LocationPlaceholder"] = ("City or country", "المدينة أو الدولة"),
        ["SearchJobs"] = ("Search jobs", "ابحث"),
        ["PopularSearches"] = ("Popular:", "الأكثر بحثاً:"),
        ["OpenJobs"] = ("open jobs", "وظيفة متاحة"),
        ["HiringCompanies"] = ("hiring companies", "شركة توظّف"),
        ["JobSeekers"] = ("job seekers", "باحث عن عمل"),
        ["LatestJobs"] = ("Latest jobs", "أحدث الوظائف"),
        ["ViewAllJobs"] = ("All jobs", "كل الوظائف"),
        ["NoJobsYet"] = ("No jobs yet — check back soon.", "لا توجد وظائف بعد — عد قريباً."),
        ["TopCompanies"] = ("Top hiring companies", "أبرز الشركات الموظِّفة"),
        ["JobsCount"] = ("{0} jobs", "{0} وظائف"),
        ["SeekerCtaTitle"] = ("Looking for a job?", "تبحث عن عمل؟"),
        ["SeekerCtaText"] = ("Create a free profile, upload your CV, and apply in one click.", "أنشئ ملفاً مجانياً، ارفع سيرتك الذاتية، وقدّم بنقرة واحدة."),
        ["CreateFreeProfile"] = ("Create free profile", "أنشئ ملفاً مجانياً"),
        ["EmployerCtaTitle"] = ("Hiring?", "توظّف؟"),
        ["EmployerCtaText"] = ("Post jobs and let AI rank your applicants with evidence from their CVs.", "انشر الوظائف ودع الذكاء الاصطناعي يرتب المتقدمين مع أدلة من سيرهم الذاتية."),
        ["PostJobFree"] = ("Post a job", "انشر وظيفة"),
        ["EmployerHeroTitle"] = ("Hire faster with AI that reads CVs like a recruiter", "وظّف أسرع بذكاء اصطناعي يقرأ السير الذاتية كمسؤول توظيف"),
        ["EmployerHeroText"] = ("Post jobs, get applicants ranked by real fit, and search a bilingual CV database in plain language.", "انشر الوظائف، واحصل على المتقدمين مرتبين حسب التطابق الحقيقي، وابحث في قاعدة سير ذاتية ثنائية اللغة بلغة طبيعية."),
        ["EmpFeature1Title"] = ("Post jobs", "انشر الوظائف"),
        ["EmpFeature1Text"] = ("Publish openings on a job board built for the region, in Arabic or English.", "انشر فرصك على منصة وظائف مصممة للمنطقة، بالعربية أو الإنجليزية."),
        ["EmpFeature2Title"] = ("AI-ranked applicants", "ترتيب المتقدمين بالذكاء الاصطناعي"),
        ["EmpFeature2Text"] = ("Every applicant gets a match score, a reason, and quotes from their CV.", "كل متقدم يحصل على درجة تطابق وسبب واقتباسات من سيرته الذاتية."),
        ["EmpFeature3Title"] = ("Search the CV database", "ابحث في قاعدة السير الذاتية"),
        ["EmpFeature3Text"] = ("\"Python developer with 5+ years\" — find people who never applied yet.", "«مطور بايثون خبرة 5 سنوات» — اعثر على أشخاص لم يتقدموا بعد."),
        ["EmpFeature4Title"] = ("Your private talent pool", "بنك المواهب الخاص بك"),
        ["EmpFeature4Text"] = ("Upload CVs you already have; they stay private to your company.", "ارفع السير الذاتية التي لديك؛ تبقى خاصة بشركتك."),

        // ---------------- account
        ["CreateAccount"] = ("Create account", "إنشاء حساب"),
        ["CreateSeekerAccount"] = ("Create your job seeker account", "أنشئ حساب الباحث عن عمل"),
        ["CreateSeekerHint"] = ("Free. Upload your CV next and we'll build your profile automatically.", "مجاني. ارفع سيرتك الذاتية بعدها وسنبني ملفك تلقائياً."),
        ["CreateEmployerAccount"] = ("Create employer account", "إنشاء حساب صاحب عمل"),
        ["CreateEmployerHint"] = ("New companies are reviewed by our team before jobs go live.", "تتم مراجعة الشركات الجديدة من فريقنا قبل نشر الوظائف."),
        ["CompanyName"] = ("Company name", "اسم الشركة"),
        ["AreYouEmployer"] = ("Hiring?", "توظّف؟"),
        ["RegisterAsEmployer"] = ("Create an employer account", "أنشئ حساب صاحب عمل"),
        ["LookingForJob"] = ("Looking for a job?", "تبحث عن عمل؟"),
        ["NoAccount"] = ("New to TalentLens?", "جديد على TalentLens؟"),
        ["HaveAccount"] = ("Already have an account?", "لديك حساب بالفعل؟"),
        ["RememberMe"] = ("Remember me", "تذكرني"),
        ["InvalidLogin"] = ("Invalid email or password.", "البريد الإلكتروني أو كلمة المرور غير صحيحة."),
        ["LockedOut"] = ("This account is locked. Try again later or contact support.", "هذا الحساب مقفل. حاول لاحقاً أو تواصل مع الدعم."),
        ["WelcomeSeeker"] = ("Welcome! Upload your CV to build your profile.", "أهلاً بك! ارفع سيرتك الذاتية لبناء ملفك."),
        ["WelcomeEmployer"] = ("Welcome! Post your first job.", "أهلاً بك! انشر وظيفتك الأولى."),
        ["WelcomeEmployerPending"] = ("Welcome! Your company is awaiting approval — you can prepare job drafts meanwhile.", "أهلاً بك! شركتك بانتظار الموافقة — يمكنك إعداد مسودات الوظائف في الأثناء."),

        // ---------------- jobs (public)
        ["JobType"] = ("Job type", "نوع الوظيفة"),
        ["Workplace"] = ("Workplace", "مكان العمل"),
        ["JobsFound"] = ("{0} jobs found", "{0} وظيفة"),
        ["NoJobsFound"] = ("No jobs match your search. Try other words or remove filters.", "لا توجد وظائف مطابقة. جرّب كلمات أخرى أو أزل الفلاتر."),
        ["AppliedBadge"] = ("Applied", "تم التقديم"),
        ["JobDescription"] = ("Job description", "الوصف الوظيفي"),
        ["Requirements"] = ("Requirements", "المتطلبات"),
        ["MoreJobsAt"] = ("More jobs at {0}", "وظائف أخرى في {0}"),
        ["YouApplied"] = ("You applied", "لقد تقدمت"),
        ["TrackApplications"] = ("Track your applications", "تابع طلباتك"),
        ["ApplyForJob"] = ("Apply for this job", "قدّم على هذه الوظيفة"),
        ["ApplyNeedsCv"] = ("Upload your CV first — companies see it when you apply.", "ارفع سيرتك الذاتية أولاً — تراها الشركات عند التقديم."),
        ["CoverLetterOptional"] = ("Cover letter (optional)", "رسالة تعريفية (اختياري)"),
        ["ApplyNow"] = ("Apply now", "قدّم الآن"),
        ["SignInToApply"] = ("Create a free profile or sign in to apply.", "أنشئ ملفاً مجانياً أو سجّل الدخول للتقديم."),
        ["OnlySeekersApply"] = ("Only job seeker accounts can apply.", "يمكن لحسابات الباحثين عن عمل فقط التقديم."),
        ["HowWellYouMatch"] = ("How well do you match?", "ما مدى تطابقك؟"),
        ["MatchHint"] = ("Our AI reads your CV against this job and shows the evidence.", "يقرأ الذكاء الاصطناعي سيرتك مقابل هذه الوظيفة ويعرض الأدلة."),
        ["CheckMyMatch"] = ("Check my match", "افحص تطابقي"),
        ["MatchNeedsCv"] = ("Available once your CV is processed.", "متاح بعد معالجة سيرتك الذاتية."),
        ["YourMatch"] = ("Your match", "تطابقك"),
        ["ViewCompany"] = ("Company page", "صفحة الشركة"),
        ["Applied"] = ("Application sent for {0}. Good luck!", "تم إرسال طلبك لوظيفة {0}. بالتوفيق!"),
        ["AlreadyApplied"] = ("You already applied to this job.", "لقد تقدمت لهذه الوظيفة مسبقاً."),
        ["SearchCompanies"] = ("Search companies…", "ابحث عن شركة…"),
        ["NoCompanies"] = ("No companies found.", "لا توجد شركات."),
        ["OpenJobsAt"] = ("Open jobs at {0}", "الوظائف المتاحة في {0}"),
        ["NoOpenJobs"] = ("No open jobs right now.", "لا توجد وظائف متاحة حالياً."),
        ["Employees"] = ("{0} employees", "{0} موظف"),

        // ---------------- seeker
        ["HelloName"] = ("Hello, {0}", "مرحباً، {0}"),
        ["ProfileStrength"] = ("Profile strength", "قوة الملف"),
        ["UploadCvToStart"] = ("Upload your CV to get started", "ارفع سيرتك الذاتية للبدء"),
        ["CompleteProfile"] = ("Complete your profile", "أكمل ملفك"),
        ["Applications"] = ("Applications", "الطلبات"),
        ["InterviewsOffers"] = ("Interviews & offers", "مقابلات وعروض"),
        ["RecommendedForYou"] = ("Recommended for you", "وظائف مقترحة لك"),
        ["NoRecommendations"] = ("Add skills to your profile (or upload your CV) to get recommendations.", "أضف مهاراتك إلى ملفك (أو ارفع سيرتك) لتحصل على اقتراحات."),
        ["RecentApplications"] = ("Recent applications", "آخر الطلبات"),
        ["NoApplicationsYet"] = ("You haven't applied to any jobs yet.", "لم تتقدم لأي وظيفة بعد."),
        ["MyCv"] = ("My CV", "سيرتي الذاتية"),
        ["NoCvYet"] = ("No CV yet. Upload one and we'll fill your profile automatically.", "لا توجد سيرة ذاتية بعد. ارفعها وسنملأ ملفك تلقائياً."),
        ["UploadCv"] = ("Upload CV", "رفع السيرة الذاتية"),
        ["ReplaceCv"] = ("Replace CV", "استبدال السيرة الذاتية"),
        ["CvProcessing"] = ("Reading your CV… this takes a few seconds.", "جارٍ قراءة سيرتك الذاتية… يستغرق ذلك ثوانٍ."),
        ["CvUploaded"] = ("CV uploaded. We're reading it now.", "تم رفع السيرة الذاتية. نقرؤها الآن."),
        ["Headline"] = ("Headline", "المسمى المهني"),
        ["HeadlinePlaceholder"] = ("e.g. Senior Backend Developer", "مثال: مطور خلفيات أول"),
        ["YearsExperience"] = ("Years of experience", "سنوات الخبرة"),
        ["About"] = ("About me", "نبذة عني"),
        ["VisibleToRecruiters"] = ("Let recruiters find me in the CV database", "اسمح لمسؤولي التوظيف بإيجادي في قاعدة السير الذاتية"),
        ["VisibleToRecruitersHint"] = ("Companies you apply to can always see your profile.", "الشركات التي تتقدم لها يمكنها دائماً رؤية ملفك."),
        ["SaveProfile"] = ("Save profile", "حفظ الملف"),
        ["ProfileSaved"] = ("Profile saved.", "تم حفظ الملف."),
        ["FromYourCv"] = ("From your CV", "من سيرتك الذاتية"),
        ["JobTitles"] = ("Job titles", "المسميات الوظيفية"),
        ["AppliedAgo"] = ("Applied {0}", "تم التقديم {0}"),
        ["Withdraw"] = ("Withdraw application", "سحب الطلب"),
        ["ConfirmWithdraw"] = ("Withdraw this application?", "سحب هذا الطلب؟"),
        ["Withdrawn"] = ("Application withdrawn.", "تم سحب الطلب."),
        ["NoSavedJobs"] = ("No saved jobs. Tap ☆ on any job to save it.", "لا توجد وظائف محفوظة. اضغط ☆ على أي وظيفة لحفظها."),

        // ---------------- employer
        ["EmployerDashboard"] = ("Employer dashboard", "لوحة صاحب العمل"),
        ["Applicants"] = ("Applicants", "المتقدمون"),
        ["NewApplicants"] = ("New applicants", "متقدمون جدد"),
        ["ApplicantsCount"] = ("{0} applicants", "{0} متقدم"),
        ["NewCount"] = ("{0} new", "{0} جديد"),
        ["NoJobsPosted"] = ("No jobs yet.", "لا توجد وظائف بعد."),
        ["RecentApplicants"] = ("Recent applicants", "آخر المتقدمين"),
        ["NoApplicantsYet"] = ("No applicants yet.", "لا يوجد متقدمون بعد."),
        ["JobTitle"] = ("Job title", "المسمى الوظيفي"),
        ["JobTitlePlaceholder"] = ("e.g. Senior .NET Developer", "مثال: مطور .NET أول"),
        ["EditJob"] = ("Edit job", "تعديل الوظيفة"),
        ["MinYears"] = ("Minimum years of experience", "الحد الأدنى لسنوات الخبرة"),
        ["RequiredSkills"] = ("Required skills", "المهارات المطلوبة"),
        ["SkillsHintAi"] = ("Comma-separated. The AI uses them to rank applicants.", "افصل بفواصل. يستخدمها الذكاء الاصطناعي لترتيب المتقدمين."),
        ["SalaryFrom"] = ("Salary from", "الراتب من"),
        ["SalaryTo"] = ("Salary to", "الراتب إلى"),
        ["SalaryRange"] = ("The maximum salary must be above the minimum.", "يجب أن يكون الحد الأعلى للراتب أكبر من الأدنى."),
        ["Currency"] = ("Currency", "العملة"),
        ["SaveDraft"] = ("Save draft", "حفظ كمسودة"),
        ["SaveAndPublish"] = ("Save & publish", "حفظ ونشر"),
        ["Publish"] = ("Publish", "نشر"),
        ["Reopen"] = ("Reopen", "إعادة فتح"),
        ["CloseJob"] = ("Close", "إغلاق"),
        ["ConfirmCloseJob"] = ("Close this job? It will disappear from the job board.", "إغلاق هذه الوظيفة؟ ستختفي من لوحة الوظائف."),
        ["JobSaved"] = ("Job saved as a draft.", "تم حفظ الوظيفة كمسودة."),
        ["JobPublished"] = ("Job published — it's live on the job board.", "تم نشر الوظيفة على لوحة الوظائف."),
        ["JobClosed"] = ("Job closed.", "تم إغلاق الوظيفة."),
        ["CompanyNotApproved"] = ("Your company is not approved yet, so jobs are kept as drafts until an admin approves it.", "لم تتم الموافقة على شركتك بعد، لذا تبقى الوظائف مسودات حتى موافقة الإدارة."),
        ["RankWithAi"] = ("Rank with AI", "رتّب بالذكاء الاصطناعي"),
        ["RankHint"] = ("The AI compares every applicant's CV with this job and explains each score with quotes from the CV.", "يقارن الذكاء الاصطناعي سيرة كل متقدم بهذه الوظيفة ويشرح كل درجة باقتباسات من السيرة."),
        ["Ranked"] = ("Ranked {0} applicants.", "تم ترتيب {0} متقدم."),
        ["NothingToRank"] = ("No applicants with a processed CV to rank yet.", "لا يوجد متقدمون بسير ذاتية معالجة بعد."),
        ["SortBy"] = ("Sort:", "ترتيب:"),
        ["BestMatch"] = ("Best match", "الأفضل تطابقاً"),
        ["Newest"] = ("Newest", "الأحدث"),
        ["CvNotReady"] = ("CV not processed yet", "لم تتم معالجة السيرة بعد"),
        ["CoverLetter"] = ("Cover letter", "الرسالة التعريفية"),
        ["PrivateNote"] = ("Private note (only your team sees it)", "ملاحظة خاصة (يراها فريقك فقط)"),
        ["StatusUpdated"] = ("Application updated.", "تم تحديث الطلب."),
        ["AppliedToYourJobs"] = ("Applied to your jobs", "تقدم لوظائفك"),
        ["TalentPoolHint"] = ("CVs you upload here are private to your company and searchable with CV search.", "السير الذاتية التي ترفعها هنا خاصة بشركتك ويمكن البحث فيها."),
        ["SearchIn"] = ("Search in", "ابحث في"),
        ["ScopeSeekers"] = ("Job seekers database", "قاعدة الباحثين عن عمل"),
        ["ScopeTalentPool"] = ("My talent pool", "بنك مواهبي"),
        ["ScopeSeekersHint"] = ("Job seekers on TalentLens who chose to be visible to recruiters.", "الباحثون عن عمل على TalentLens الذين اختاروا الظهور لمسؤولي التوظيف."),
        ["ScopeTalentPoolHint"] = ("CVs your team uploaded — private to your company.", "السير الذاتية التي رفعها فريقك — خاصة بشركتك."),
        ["CompanySize"] = ("Company size", "حجم الشركة"),
        ["AboutCompany"] = ("About the company", "عن الشركة"),
        ["CompanySaved"] = ("Company profile saved.", "تم حفظ ملف الشركة."),
        ["ViewPublicPage"] = ("View public page", "عرض الصفحة العامة"),

        // ---------------- talent pool / CV search (carried over)
        ["SearchPlaceholder"] = ("e.g. Python developer with 5+ years, speaks English", "مثال: مطور بايثون خبرة 5 سنوات يتحدث الإنجليزية"),
        ["UploadCvs"] = ("Upload CVs", "رفع سير ذاتية"),
        ["NoCandidatesYet"] = ("No CVs yet. Upload some to get started.", "لا توجد سير ذاتية بعد. ارفع بعضها للبدء."),
        ["RecentSearches"] = ("Recent searches", "عمليات البحث الأخيرة"),
        ["ResultsCount"] = ("{0} results", "{0} نتيجة"),
        ["NoSearchesYet"] = ("No searches yet.", "لا توجد عمليات بحث بعد."),
        ["FilterByName"] = ("Filter by name, email or file…", "تصفية بالاسم أو البريد أو الملف…"),
        ["AllStatuses"] = ("All statuses", "كل الحالات"),
        ["AutoRefresh"] = ("Some CVs are still being processed — this page refreshes automatically.", "بعض السير الذاتية ما زالت قيد المعالجة — تتحدث الصفحة تلقائياً."),
        ["NoFilesSelected"] = ("Choose at least one file.", "اختر ملفاً واحداً على الأقل."),
        ["UnsupportedType"] = ("only PDF and DOCX files are supported", "الملفات المدعومة هي PDF و DOCX فقط"),
        ["FileTooLarge"] = ("file is empty or larger than {0} MB", "الملف فارغ أو أكبر من {0} ميغابايت"),
        ["ContentMismatch"] = ("file content does not match its extension", "محتوى الملف لا يطابق امتداده"),
        ["UploadInfected"] = ("the file was blocked by the security scan", "تم حظر الملف بواسطة الفحص الأمني"),
        ["UploadScanFailed"] = ("the security scan is unavailable — please try again in a few minutes", "الفحص الأمني غير متاح — يرجى المحاولة بعد دقائق"),
        ["TooManyRequests"] = ("Too many requests", "طلبات كثيرة جداً"),
        ["TooManyRequestsText"] = ("You're going a bit fast. Please wait {0} seconds and try again.", "أنت تُسرع قليلاً. يرجى الانتظار {0} ثانية ثم المحاولة مجدداً."),
        ["FilesQueued"] = ("{0} CV(s) uploaded and queued for processing.", "تم رفع {0} سيرة ذاتية ووضعها في قائمة المعالجة."),
        ["RetryQueued"] = ("Queued for processing again.", "أُعيدت إلى قائمة المعالجة."),
        ["CandidateDeleted"] = ("Deleted {0}.", "تم حذف {0}."),
        ["DropHere"] = ("Drop CVs here or click to choose", "أفلت السير الذاتية هنا أو انقر للاختيار"),
        ["UploadHint"] = ("PDF or DOCX, up to {0} MB. Arabic and English are both supported.", "PDF أو DOCX، حتى {0} ميغابايت. العربية والإنجليزية مدعومتان."),
        ["UploadAndProcess"] = ("Upload & process", "رفع ومعالجة"),
        ["WhatHappensNext"] = ("What happens next?", "ماذا يحدث بعد ذلك؟"),
        ["WhatHappensNextText"] = (
            "Each CV is split into sections, embedded for semantic search, indexed for keyword search, and its profile (name, skills, years of experience…) is extracted. It takes a few seconds per CV.",
            "تُقسَّم كل سيرة ذاتية إلى أقسام، وتُحوَّل إلى متجهات للبحث الدلالي، وتُفهرس للبحث بالكلمات، ويُستخرج ملفها (الاسم، المهارات، سنوات الخبرة…). يستغرق ذلك بضع ثوانٍ لكل ملف."),
        ["DownloadCv"] = ("CV", "السيرة الذاتية"),
        ["Reprocess"] = ("Reprocess", "إعادة المعالجة"),
        ["ConfirmDelete"] = ("Delete this candidate and their CV? This cannot be undone.", "حذف هذا المرشح وسيرته الذاتية؟ لا يمكن التراجع."),
        ["ProcessingFailed"] = ("Processing failed", "فشلت المعالجة"),
        ["StillProcessing"] = ("This CV is still being processed…", "ما زالت هذه السيرة الذاتية قيد المعالجة…"),
        ["TopK"] = ("Number of results", "عدد النتائج"),
        ["TopN"] = ("Top {0}", "أفضل {0}"),
        ["TryExamples"] = ("Try:", "جرّب:"),
        ["SearchFailed"] = ("Search failed", "فشل البحث"),
        ["ResultsFor"] = ("{0} candidates for", "{0} مرشح لـ"),
        ["NoResults"] = ("No matching candidates. Try fewer requirements or different words.", "لا يوجد مرشحون مطابقون. جرّب متطلبات أقل أو كلمات مختلفة."),
        ["MatchScore"] = ("Match score", "درجة التطابق"),
        ["WhyCandidate"] = ("Why this candidate?", "لماذا هذا المرشح؟"),
        ["AiUnavailable"] = ("The AI service is not reachable. Is it running?", "تعذر الوصول إلى خدمة الذكاء الاصطناعي. هل هي قيد التشغيل؟"),
        ["AiOnline"] = ("AI service online", "خدمة الذكاء الاصطناعي تعمل"),
        ["AiOffline"] = ("AI service offline", "خدمة الذكاء الاصطناعي متوقفة"),

        // ---------------- admin
        ["AdminOverview"] = ("Platform overview", "نظرة عامة على المنصة"),
        ["Recruiters"] = ("Recruiters", "مسؤولو التوظيف"),
        ["ActiveCompanies"] = ("Active companies", "شركات نشطة"),
        ["PendingCompanies"] = ("Pending companies", "شركات بانتظار الموافقة"),
        ["CvsProcessed"] = ("CVs processed", "سير ذاتية معالجة"),
        ["AwaitingApproval"] = ("Companies awaiting approval", "شركات بانتظار الموافقة"),
        ["NothingPending"] = ("Nothing pending. 🎉", "لا يوجد شيء معلق. 🎉"),
        ["Approve"] = ("Approve", "موافقة"),
        ["Reactivate"] = ("Reactivate", "إعادة تفعيل"),
        ["Suspend"] = ("Suspend", "إيقاف"),
        ["ConfirmSuspend"] = ("Suspend this company? Its jobs will be hidden.", "إيقاف هذه الشركة؟ ستُخفى وظائفها."),
        ["CompanyApproved"] = ("{0} is now active.", "{0} أصبحت نشطة."),
        ["CompanySuspended"] = ("{0} was suspended.", "تم إيقاف {0}."),
        ["SearchUsers"] = ("Name or email…", "الاسم أو البريد…"),
        ["SearchJobsAdmin"] = ("Job or company…", "الوظيفة أو الشركة…"),
        ["Locked"] = ("Locked", "مقفل"),
        ["Lock"] = ("Lock", "قفل"),
        ["Unlock"] = ("Unlock", "فتح"),
        ["UserLocked"] = ("User locked and signed out.", "تم قفل المستخدم وتسجيل خروجه."),
        ["UserUnlocked"] = ("User unlocked.", "تم فتح المستخدم."),
        ["CannotLockSelf"] = ("You can't lock your own account.", "لا يمكنك قفل حسابك."),

        // ---------------- CV sections (evidence labels)
        ["Section_header"] = ("Header", "البيانات الشخصية"),
        ["Section_summary"] = ("Summary", "الملخص"),
        ["Section_experience"] = ("Experience", "الخبرات"),
        ["Section_education"] = ("Education", "التعليم"),
        ["Section_skills"] = ("Skills", "المهارات"),
        ["Section_projects"] = ("Projects", "المشاريع"),
        ["Section_certifications"] = ("Certifications", "الشهادات"),
        ["Section_languages"] = ("Languages", "اللغات"),
        ["Section_other"] = ("Other", "أخرى"),
    };

    public static IReadOnlyCollection<string> Keys => Texts.Keys;

    public bool IsArabic => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ar";

    public string this[string key] =>
        Texts.TryGetValue(key, out var text) ? (IsArabic ? text.Ar : text.En) : key;

    /// <summary>Formatted text, e.g. T.F("ResultsCount", 7) → "7 results".</summary>
    public string F(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, this[key], args);

    /// <summary>Display name for a CV section id ("experience" → "Experience" / "الخبرات").</summary>
    public string Section(string section) =>
        Texts.ContainsKey($"Section_{section}") ? this[$"Section_{section}"] : section;

    /// <summary>"1 year of experience" / "6 years of experience" (and the Arabic forms).</summary>
    public string Years(double years) => years == 1 ? this["YearsOne"] : F("YearsLong", years);

    /// <summary>"Today", "Yesterday", "5 days ago", "2 months ago".</summary>
    public string Ago(DateTime utc)
    {
        var days = (int)(DateTime.UtcNow.Date - utc.Date).TotalDays;
        return days switch
        {
            <= 0 => this["AgoToday"],
            1 => this["AgoYesterday"],
            < 60 => F("AgoDays", days),
            _ => F("AgoMonths", days / 30),
        };
    }
}
